Added Linting and Prettier workflow Action
dokc/rap-god-api pull request #22
Opened 2022-03-19 15:39 UTC by chetak123

## Related Issue

- Fixes #11  (issue) 

## Proposed Changes 

I have added [prettier](https://github.com/marketplace/actions/prettier-action) and [Super-Linter ](https://github.com/marketplace/actions/super-linter) Workflow Action

## Additional Info

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2022-03-21 06:46 UTC, AbhijithGanesh requested changes

2022-03-21 06:46 UTC, AbhijithGanesh commented on .github/workflows/linter.yml
> +    branches: [master, main]
Please remove `master`

2022-03-25 12:51 UTC, AbhijithGanesh reviewed
Look

2022-03-25 12:51 UTC, AbhijithGanesh commented on .github/workflows/prettier.yml
> +  pull_request:
can you add branches here?

2022-03-25 12:52 UTC, AbhijithGanesh approved these changes
Looks Good to Me

2022-03-25 13:11 UTC, shreemaan-abhishek reviewed
LGTM as well but how do we make sure that this works as intended.

2022-03-25 13:44 UTC, chetak123 commented
hey @shreemaan-abhishek the prettier.yml worked here https://github.com/dokc/rap-god-api/pull/20/commits/79339b44b55a218e6d981ad84d94e0342ef5c057

2022-03-25 16:19 UTC, shreemaan-abhishek commented
Cool stuff!

2022-03-25 16:20 UTC, merged