added schema
dokc/rap-god-api pull request #29
Opened 2022-04-08 12:07 UTC by chetak123

changes

## Related Issue 

- Fixes #27 

## Proposed Changes 

- Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## Additional Info

- Any additional information, context or references. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2022-04-11 02:59 UTC, AbhijithGanesh requested changes

2022-04-11 02:59 UTC, AbhijithGanesh commented on src/models/rapTb.js
> +}
Please make it as a field and then export it please, it will be much better that way.

2022-04-11 02:59 UTC, AbhijithGanesh commented on src/models/rapTb.js
> +  key: [["rap_id"],"lyricist_name"]
```suggestion
  key: ["rap_id","lyricist_name"]
```
`rap_id` is not nested JSON, therefore it can be called directly I suppose

2022-04-11 02:59 UTC, AbhijithGanesh commented on src/models/rapTb.js
> +      date_of_release :"date",
```suggestion
      date_of_release :{
      type:"date",
      default: {"$db_function": "toTimestamp(now())"}
      },
```
It is better to have a good timestamp default function

2022-04-11 03:01 UTC, AbhijithGanesh commented
This documentation will require changes that will need documentation, schema goes on the website and it is essential.

2022-04-11 06:42 UTC, shreemaan-abhishek commented on src/models/rapTb.js
> +      date_of_release :"date",
What does the file name `rapTb.js` mean?

2022-04-12 12:48 UTC, shreemaan-abhishek commented on src/models/rapTb.js
> +      date_of_release :"date",
@yashgangwar7558  @AmitKarnam  @AbhijithGanesh would you like to see any changes in the file naming?

2022-04-12 12:53 UTC, shreemaan-abhishek reviewed
@AbhijithGanesh for this change I think we will have to co-ordinate with Shivam for docs into the website?

2022-04-14 10:42 UTC, AbhijithGanesh approved these changes
LGTM

2022-04-14 12:31 UTC, merged