Added User model and corresponding routes
dokc/rap-god-api pull request #41
Opened 2022-05-04 18:23 UTC by AmitKarnam

## Related Issue
User registration and login issue

## Proposed Changes 
Created a user schema and added routes to register an user and login a user

2022-05-05 06:49 UTC, AbhijithGanesh requested changes

2022-05-05 06:49 UTC, AbhijithGanesh commented on src/models/UserModel.js
> +  key : ["email"],
I think fast name should be a key as well

2022-05-05 06:49 UTC, AbhijithGanesh commented on src/models/UserModel.js
> +  key : ["email"],
```suggestion
  key : ["email", "fast_name"],
```

2022-05-05 06:49 UTC, AbhijithGanesh commented on src/routes/loginRouter.js
> +        const user = await models.instance.users.find({email});
I am not sure if this will find the model directly, I think it is better to do a 
```json
{
email: Email
}
```

2022-05-05 06:49 UTC, AbhijithGanesh commented on src/models/UserModel.js
> +    password   : "text"
I think the password can be hashed like this instead of the router hashing it
```
  methods: {
        setPassword: function (password, callback) {
          crypto.pbkdf2Sync('secret', 'salt', 100000, 512, 'sha512', function(err, hashed) {
            if (err) { return callback(err); }
            this.password_hash = hashed;
            return callback();
          });
        }
    },
```

2022-05-05 12:18 UTC, AmitKarnam commented on src/models/UserModel.js
> +  key : ["email"],
It was supposed to be last name!

2022-05-05 12:19 UTC, AmitKarnam commented on src/routes/loginRouter.js
> +        const user = await models.instance.users.find({email});
Can you please elaborate this point. @AbhijithGanesh

2022-05-10 13:23 UTC, AbhijithGanesh commented on src/routes/loginRouter.js
> +        const user = await models.instance.users.find({email});
Its better to serialize the json the way I had mentioned in the comment because we may end up with an error otherwise(we may not too but the way I told is a safer way to do it)

2022-06-29 13:52 UTC, cnu1812 commented
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Readable, Efficient, Elegant

2022-08-04 10:09 UTC, merged